### ISSUE TITLE
Locate dataset and train.py suitable for demo AML  pipeline flow

### ISSUE THREAD

**Issue by olgaliak** [olgaliak/seismic-deeplearning#2]
Work with Deepseimic team and pick a dataset that we can use to run AML pipeline on

**Comment by annazietlow** [comment]
Train file: https://github.com/microsoft/seismic-deeplearning/blob/staging/experiments/interpretation/dutchf3_patch/local/train.py with https://github.com/microsoft/seismic-deeplearning/blob/staging/experiments/interpretation/dutchf3_patch/local/configs/unet.yaml and dutchf3 data
