### ISSUE TITLE
TestLoader's support for custom paths

### ISSUE THREAD

**Issue by olgaliak** [olgaliak/seismic-deeplearning#8]
Currently the code assumes hardcoded "test" folders and splits. 
Support for custom paths will make it possible to easily test on separate volumes of seismic data.

**Comment by maxkazmsft** [comment]
Discussed - this should go as a PR directly into the staging branch of the main repo.

TODO: please add a regression test to make sure that when your optional parameters are turned off the original script still produces the same result before you added the optional parameters.

**Comment by GeisaFaustino** [comment]
Pull request successfully merged and closed
https://github.com/microsoft/seismic-deeplearning/pull/196
